name: web
version: '0.2.0.0'
category: Language
author: Markus Läll
maintainer: markus.l2ll@gmail.com
license: GPL-2
default-extensions:
- Arrows
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- EmptyDataDecls
- ExtendedDefaultRules
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeFamilies
- TypeInType
- TypeOperators
- TypeSynonymInstances
- UndecidableInstances
dependencies:
- base
- cookie
- lens-aeson
- directory
- transformers
- wreq
- vector
- hs-minu
- web-js
- lens
- aeson
- async
- blaze-builder
- boomerang
- bytestring
- case-insensitive
- containers
- dlist
- ds
- file-embed
- hashable
- http-types
- identifiers
- mime-types
- mtl
- network
- network-simple
- tagged
- template-haskell
- text
- text-format
- unordered-containers
- wai
- warp
- warp-tls
- web-browser
- web-url
- render
- rapid
- mysql-simple
- cryptonite
- memory
- base64-bytestring
- process

library:
  exposed-modules:
  - Cookie
  - DOM.Core
  - DOM.Event
  - DOM.JS
  - DOM
  - HTTP.Common
  - HTTP.Header
  - HTTP.Response
  - HTTP.Response.InlineFile
  - URL.ToPayload
  - Warp_Helpers
  - Web
  - CSS
  - SVG
  - HTML
  - Web.CSS
  - Web.Endpoint
  - Web.FRP
  - Web.Monad
  - Web.Response
  - XML
  - XML.Core
  - JS.Upstream
  - X
  - X.DOM
  - X.Auth.Google
  other-modules:
  - Pr
  - TH
  - CSS.Internal
  - CSS.Monad
  - CSS.Shorthands
  - HTML.Core
  - HTML.Paste
  - SVG.Attributes
  - SVG.Elements
  dependencies:
  - base
  - aeson
  - async
  - blaze-builder
  - boomerang
  - bytestring
  - case-insensitive
  - containers
  - dlist
  - ds
  - file-embed
  - hashable
  - http-types
  - identifiers
  - lens
  - mime-types
  - mtl
  - network
  - network-simple
  - tagged
  - template-haskell
  - text
  - text-format
  - unordered-containers
  - wai
  - warp
  - warp-tls
  - web-browser
  - web-url
  - render
