resolver: lts-7.12
packages:
- '.'
- location: '../hs-minu'
  extra-dep: true
- location: '../web-browser'
  extra-dep: true
- location: '../web-js'
  extra-dep: true
- location:
    git: git://git-daemon/identifiers
    commit: master
  extra-dep: true
- location: '../render'
  extra-dep: true
- location: '../ds'
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
extra-include-dirs: [/usr/local/opt/openssl/include]
extra-lib-dirs: [/usr/local/opt/openssl/lib]
