name: web
version: '0.2.0.0'
category: Language
author: Markus Läll
maintainer: markus.l2ll@gmail.com
license: GPL-2
dependencies:
- base
- cookie
- lens-aeson
- directory
- transformers
- wreq
- vector
- lens
- aeson
- async
- blaze-builder
- boomerang
- bytestring
- case-insensitive
- containers
- dlist
- file-embed
- hashable
- http-types
- http-client
- identifiers
- mime-types
- mtl
- network
- network-simple
- tagged
- template-haskell
- text
- text-format
- unordered-containers
- wai
- wai-extra
- warp
- warp-tls
- web-browser
- web-url
- render
- rapid
- cryptonite
- memory
- base64-bytestring
- process
- time
- mwc-random
- data-default
- multiline

library:
  exposed-modules:
  - Cookie
  - DOM.Core
  - DOM.Event
  - DOM.JS
  - DOM
  - HTTP.Common
  - HTTP.Header
  - HTTP.Response
  - HTTP.Response.InlineFile
  - HTTP
  - URL.ToPayload
  - URL.TH
  - Warp_Helpers
  - Web
  - CSS
  - SVG
  - HTML
  - Web.CSS
  - Web.Endpoint
  - Web.Monad
  - Web.Response
  - XML
  - XML.Core

  - JS.Syntax
  - JS.DSL
  - JS.API
  - JS.Derive
  - JS.Lib
  - JS.Lib.Sleep
  - JS.Lib.Async
  - JS
  - JS.Roundtrip
  - IndexedDB.IDB
  - PWA
  - JW.T
  - Sessions
  - JS.TH

  - X
  - X.Prelude
  - X.Cookie
  - X.DOM
  - X.Auth.Google
  - X.Google.Maps
  - X.Google.Spreadsheet
  - X.Widgets
  - X.Widgets.Menu
  - X.Wai
  other-modules:
  - TH
  - JS.Syntax.Types
  - JS.Syntax.Render
  - JS.DSL.Identifiers
  - JS.DSL.Internal
  - CSS.Internal
  - CSS.Monad
  - CSS.Shorthands
  - HTML.Core
  - HTML.Paste
  - SVG.Attributes
  - SVG.Elements
  - XML.Render
  - Trie
  ghc-options:
  - -Wall
  - -Wno-unused-imports
  - -Wno-name-shadowing
  - -Wno-orphans
  - -Wno-missing-signatures
  - -Wno-incomplete-patterns
  - -Wno-unused-matches
  - -Wno-unused-do-bind
  - -Wno-unused-top-binds
  - -Wno-type-defaults
  - -Wno-missing-methods

default-extensions:
- Arrows
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- EmptyDataDecls
- ExtendedDefaultRules
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RankNTypes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeInType
- TypeOperators
- TypeSynonymInstances
- UndecidableInstances
