name: web
version: '0.2.0.0'
category: Language
author: Markus Läll
maintainer: markus.l2ll@gmail.com
license: GPL-2
dependencies:
- base
- cookie
- lens-aeson
- directory
- transformers
- wreq
- vector
- hs-minu
- lens
- aeson
- async
- blaze-builder
- boomerang
- bytestring
- case-insensitive
- containers
- dlist
- ds
- file-embed
- hashable
- http-types
- http-client
- identifiers
- mime-types
- mtl
- network
- network-simple
- tagged
- template-haskell
- text
- text-format
- unordered-containers
- wai
- wai-extra
- warp
- warp-tls
- web-browser
- web-url
- render
- rapid
- mysql-simple
- cryptonite
- memory
- base64-bytestring
- process

library:
  exposed-modules:
  - Cookie
  - DOM.Core
  - DOM.Event
  - DOM.JS
  - DOM
  - HTTP.Common
  - HTTP.Header
  - HTTP.Response
  - HTTP.Response.InlineFile
  - URL.ToPayload
  - URL.TH
  - Warp_Helpers
  - Web
  - CSS
  - SVG
  - HTML
  - Web.CSS
  - Web.Endpoint
  - Web.Monad
  - Web.Response
  - XML
  - XML.Core

  - JS.Types
  - JS.Syntax
  - JS.DSL
  - JS.DSL.Internal
  - JS.API
  - JS.Derive
  - JS.Lib
  - JS.Lib.Sleep
  - JS.Lib.Async
  - JS.Render
  - JS
  - JS.Roundtrip

  - X
  - X.Prelude
  - X.DOM
  - X.Auth.Google
  - X.Google.Maps
  - X.Google.Spreadsheet
  - X.Widgets
  other-modules:
  - Pr
  - TH
  - CSS.Internal
  - CSS.Monad
  - CSS.Shorthands
  - HTML.Core
  - HTML.Paste
  - SVG.Attributes
  - SVG.Elements
  - XML.Render
  - JS.Examples
  - JS.Core
  - JS.DSL.Identifiers

default-extensions:
- Arrows
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- EmptyDataDecls
- ExtendedDefaultRules
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- MultiParamTypeClasses
- NamedFieldPuns
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RankNTypes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeFamilies
- TypeInType
- TypeOperators
- TypeSynonymInstances
- UndecidableInstances
